# Generated by Django 4.1.5 on 2023-01-25 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_Users", "0002_alter_user_first_name_alter_user_last_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
    ]
